### ISSUE TITLE
Map creator should not strip "foot"

### ISSUE THREAD

**Issue by hungerburg** [andreynovikov/mapcreator#2]
Currently, "foot" tag is stripped in map creation, if I fully understand. Consequently, routes type "foot" cannot be matched for display, neither "foot=yes|dedicated" on an otherwise restricted path, nor on a cycleway shared with pedestrians; esp. useful in hiking mode (eg. where I live, long stretches of way of St. James go over cycleways).

**Comment by hungerburg** [comment]
Perhaps "natural=fell" might be nice to transfer at all; that accounts for quite some blank space in the Alps, if e.g. rendered as "heath" would make an even nicer map.

Also names of glaciers should not get stripped. Those are very prominent landmarks for hiking. Don't know where names of forests get lost…

**Comment by hungerburg** [comment]
Dear Andrey, today is the day, where children have their wishes, my wish goes for selecting "natural=rock" for inclusion into the statics. As a grown child I wish for something little. Sometimes there are e.g. pinnacles close to peaks that have names that climbers refer to them that are tagged like that. Would be nice to be able to render them in close zoom levels, like cave_entrances e.g.

**Comment by hungerburg** [comment]
Also amenity=hunting_stand comes up as something wishful for rendering in hiking mode. Both as orientation points, and also as a means to learn, why a path is a one-way one otherwise miraculously ending in the woods.

**Comment by andreynovikov** [comment]
natural=fell rejected in https://github.com/gravitystorm/openstreetmap-carto/issues/545#issuecomment-98479426 and https://github.com/gravitystorm/openstreetmap-carto/issues/545#issuecomment-341895192 but I will add is as synonym for the time-being.

**Comment by andreynovikov** [comment]
The problem with rock is that it is obviously misused too often: https://overpass-turbo.eu/s/14iS but I can add it.

**Comment by andreynovikov** [comment]
Will add hunting stands.

**Comment by andreynovikov** [comment]
As for "foot" - please describe problem more precisely with OSM examples.

**Comment by hungerburg** [comment]
Rock on ways finds something around here! This one likely is a typo for bare_rock, eg. https://www.openstreetmap.org/way/223465191 - perhaps this should be corrected in the data; nodes are a bit mixed, indeed.

The fell in the Alps is a heath. Not a biologist, but have seen both, they look very much alike.

Some samples, where foot is needed:
- A downhill track with foot=no, https://www.openstreetmap.org/way/441558821 - might render prohibited in hiking mode
- A mountain trail with foot=yes, https://www.openstreetmap.org/way/433222659 - might render available in hiking mode
- A cycleway with foot=designated, https://www.openstreetmap.org/way/368777970 - might render available in hiking mode

Please allow glaciers and forest/wood to have names.

Thank you for all the work, Trekarta makes opentstreetmap data shine :)

**Comment by andreynovikov** [comment]
Woods are specially processed, but I will think about extracting its names.

**Comment by andreynovikov** [comment]
https://www.openstreetmap.org/way/441558821 - agree
https://www.openstreetmap.org/way/433222659 - rendered correctly, do not see any problem

**Comment by andreynovikov** [comment]
Created an issue: https://github.com/andreynovikov/trekarta/issues/139
You can add more special cases there if they are different in tagging.

**Comment by andreynovikov** [comment]
See you live in Innsbruck, want to visit this city very much, hope this will happen some day. :smile:

**Comment by hungerburg** [comment]
Hello Andrey, the mountain trail with "acces=no;foot=yes" renders fine in Trekarta, because it ignores the access tag. But e.g. https://www.openstreetmap.org/way/146344616 will render just the same, though it is closed for all uses due to rock fall hazard. This problem is only visible in the modified version that I run, because I mark forbidden/private/closed paths in the style sheet. I thought I had opened an issue for Trekarta, but cannot find it now. The closed path cannot be simply removed from osm data, because it appears in printed maps and on old info boards nearby.

Innsbruck is nice indeed. Quite a number of people relocate there from Germany and other places for the recreational possibilities. They use that much more than the locals. If you happen to come there, please let me know!

**Comment by hungerburg** [comment]
From a freshly downloaded map, hunting stands appear as flags; Irregularly, squares within the downloaded area miss natural landuse base colours in any mode (none, hiking, skiing). Rocks do not appear. Guess, I will have to update Trekarta?

**Comment by andreynovikov** [comment]
I see the problem now. Yes, we did `acces=no` already but I forgot to honor it in hiking mode. Will fix it.

Yes, you have to wait for application update.

**Comment by hungerburg** [comment]
Foot keys and values are in the most recent map and everything works great. Hunting stands and rocks just the same, Now Trekarta rocks even more!
