### ISSUE TITLE
Stale amenities

### ISSUE THREAD

**Issue by hungerburg** [andreynovikov/mapcreator#4]
Hello Andrey, In September I deleted a drinking_water amenity. It is still on the map that I did download today. While other things that changed more recently are in their current form. For reference, the deleted node is https://www.openstreetmap.org/node/7823508278 - actually there is a reservoir_covered on location, https://www.openstreetmap.org/way/469056626 - Have i found a bug?

**Comment by hungerburg** [comment]
Another such stale POI https://www.openstreetmap.org/node/4850289231 - this node got merged into a building and stripped of its tag, but it shows a name in Trekarta.

**Comment by andreynovikov** [comment]
Do not see any problems at these locations.

**Comment by hungerburg** [comment]
Hmm, I did last update few days ago; there is still a well shown at the place of the reservoir, https://www.openstreetmap.org/way/469056626 - seen from Trekarta; maybe the amenity lingers there?

**Comment by andreynovikov** [comment]
I've updated map source yesterday. Please download and check once more.

**Comment by hungerburg** [comment]
Did the download, the well was still in place; later removed the downloaded area, downloaded again, and the well is gone! Strange enough, the wayside-chapel node did persist as a double feature. Maybe clean the whole data directory?

**Comment by andreynovikov** [comment]
Some problems may persist until I will publish updated version. It's coming soon.

**Comment by hungerburg** [comment]
I found out why I saw those wayside chapels twice - it was my mistake, because in my branch house names render as POIs. So no more issues. Sorry for the noise.
