### ISSUE TITLE
Stone building material is tagged as memorial stone

### ISSUE THREAD

**Issue by hungerburg** [andreynovikov/mapcreator#5]
On drinking water amenities or tourism guideposts, if they have an "operator" set in the data, this gets shown as its name - Building=roof gets shown as a rock, happens with trekarta built from current master and a very fresh map downloaded yesterday. Quite a ghostly issue :) Some tables seem out of sync between mapcreator and trekarta?

**Comment by andreynovikov** [comment]
I've made operator visible for bicycle rentals and charging stations but didn't think it will spread on other amenities, will fix it. As for rock, this should not happen, can you show an example?

**Comment by hungerburg** [comment]
I see them around this monument, https://www.openstreetmap.org/node/1237886555 - at least the roofs there look like rocks to me. I thought that's like the memorials when you last changed those C-like-arrays, it goes away when both trekarta and mapcreator are in sync.

![Screenshot_Rocks](https://user-images.githubusercontent.com/586972/110031289-037b0800-7d37-11eb-9954-83e203834e6b.png)

There are no natural=rock in the latest map 68-44 that I did download yesterday? There is a new one today 21:17

**Comment by hungerburg** [comment]
I see, these are not rocks, it's stones; in fact, the building material is stone. That is not the same as natural=stone though.

**Comment by andreynovikov** [comment]
This is not a natural stone but [memorial stone](https://wiki.openstreetmap.org/wiki/Tag:memorial%3Dstone). But still nice catch for map generation bug.

**Comment by hungerburg** [comment]
At first I thought, it was some kind of bread.

**Comment by andreynovikov** [comment]
This nice finding have lead me to another great issue: https://github.com/andreynovikov/trekarta/commit/197d71654fc2594e976e5d5158c9e4c3719ddc83

**Comment by hungerburg** [comment]
The operators as names and the glaciers, the glaciers! Just as a reminder :) Woods seem complex though…

**Comment by andreynovikov** [comment]
What's the problem with operators? I've made it to work only for fuel and charging stations:
https://github.com/andreynovikov/mapcreator/blob/5e01fa5c47a70f680296b31e6ff299b0850fdba1/mappings.py#L83

**Comment by hungerburg** [comment]
Operators show on amenity=drinking_water. E.g. https://www.openstreetmap.org/node/6621364823 - blame shows change from last month, map 68/44 is green in Trekarta
